[[section-context-and-scope]]
== Context and Scope

ifdef::arc42help[]
[role="arc42help"]
****
.Contents
Context and scope - as the name suggests - delimits your system (i.e. your scope) from all its communication partners
(neighboring systems and users, i.e. the context of your system). It thereby specifies the external interfaces.

If necessary, differentiate the business context (domain specific inputs and outputs) from the technical context (channels, protocols, hardware).

.Motivation
The domain interfaces and technical interfaces to communication partners are among your system's most critical aspects. Make sure that you completely understand them.

.Form
Various options:

* Context diagrams
* Lists of communication partners and their interfaces.

.tpo42 Integration
Business context is defined in req42 Chapter 3 (Scope). Technical context adds the architectural perspective with specific protocols, channels, and implementation details.

.Further Information

See https://docs.arc42.org/section-3/[Context and Scope] in the arc42 documentation.

****
endif::arc42help[]

=== Business Context

ifdef::arc42help[]
[role="arc42help"]
****
.Contents
Specification of *all* communication partners (users, IT-systems, ...) with explanations of domain specific inputs and outputs or interfaces.
Optionally you can add domain specific formats or communication protocols.

.Motivation
All stakeholders should understand which data are exchanged with the environment of the system.

.Form
All kinds of diagrams that show the system as a black box and specify the domain interfaces to communication partners.

Alternatively (or additionally) you can use a table.
The title of the table is the name of your system, the three columns contain the name of the communication partner, the inputs, and the outputs.

.tpo42 Integration
Business context is included from req42 Chapter 3 (Scope). This ensures consistency between business requirements and architectural documentation.

****
endif::arc42help[]

include::../req42-chapters/03_scope.adoc[tag=business_context]

=== Technical Context

ifdef::arc42help[]
[role="arc42help"]
****
.Contents
Technical interfaces (channels and transmission media) linking your system to its environment. In addition a mapping of domain specific input/output to the channels, i.e. an explanation which I/O uses which channel.

.Motivation
Many stakeholders make architectural decision based on the technical interfaces between the system and its context. Especially infrastructure or hardware designers decide these technical interfaces.

.Form
E.g. UML deployment diagram describing channels to neighboring systems,
together with a mapping table showing the relationships between channels and input/output.

.tpo42 Integration
Technical context adds implementation details to the business context from req42. Focus on protocols, data formats, and communication channels that implement the business interfaces.

****
endif::arc42help[]

**<Diagram or Table>**

**<optionally: Explanation of technical interfaces>**

**<Mapping Input/Output to Channels>**

=== Organisational Context

ifdef::arc42help[]
[role="arc42help"]
****
.tpo42 Integration
Organizational context shows team boundaries that influence system boundaries (Conway's Law). Included from req42 Chapter 10 (Teams).
****
endif::arc42help[]

include::../req42-chapters/10_teams.adoc[tag=teams_overview]
