[[section-technical-risks]]
== Risks and Technical Debts

ifdef::tpo42help[]
[role="tpo42help"]
****
.Contents
A list of identified technical risks or technical debts, ordered by priority

.Motivation
"Risk management is project management for grown-ups" (Tim Lister, Atlantic Systems Guild.)

This should be your motto for systematic detection and evaluation of risks and technical debts in the architecture, which will be needed by management stakeholders (e.g. project managers, product owners) as part of the overall risk analysis and measurement planning.

.Form
List of risks and/or technical debts, probably including suggested measures to minimize, mitigate or avoid risks or reduce technical debts.

.tpo42 Integration
Include business/project risks from req42 Chapter 12 and add architecture-specific technical risks and technical debts.

.Further Information

See https://docs.arc42.org/section-11/[Risks and Technical Debt] in the arc42 documentation.

****
endif::tpo42help[]

include::../req42-chapters/12_risks-assumptions.adoc[tag=risks]

=== Additional Technical Risks

ifdef::tpo42help[]
[role="tpo42help"]
****
.Content
if needed, add technical risks not covered in req42 business risks. Focus on architecture, implementation, and technology-specific risks.
****
endif::tpo42help[]

[cols="1,3,1,1,3,3" options="header"]
|===
|Id |Description | Probability |Impact | Possible Measures | Possible Mitigations

| TR1
| _<Technical risk description>_
| _<High\|Medium\|Low>_
| _<High\|Medium\|Low>_
a|
* _<Technical measure 1>_
* _<Technical measure 2>_
a|
* _<Technical mitigation 1>_
* _<Technical mitigation 2>_

|===

=== Technical Debts

ifdef::tpo42help[]
[role="tpo42help"]
****
.Content
Known technical shortcuts, temporary solutions, or architectural compromises that need to be addressed.
****
endif::tpo42help[]

[cols="1,3,1,2,2" options="header"]
|===
|Id |Technical Debt | Priority |Impact if not addressed | Refactoring Effort

| TD1
| _<Technical debt description>_
| _<High\|Medium\|Low>_
| _<What happens if we don't fix this>_
| _<Estimated effort to resolve>_

| TD2
| _<Technical debt description>_
| _<High\|Medium\|Low>_
| _<What happens if we don't fix this>_
| _<Estimated effort to resolve>_

|===
