[[section-glossary]]
== Glossary

ifdef::tpo42help[]
[role="tpo42help"]
****
.Contents
The most important domain and technical terms that your stakeholders use when discussing the system.

You can also see the glossary as source for translations if you work in multi-language teams.

.Motivation
You should clearly define your terms, so that all stakeholders

* have an identical understanding of these terms
* do not use synonyms and homonyms

.Form

A table with columns <Term> and <Definition>.

Potentially more columns in case you need translations.

.tpo42 Integration
Focus on technical implementation terms that developers and architects need. Business domain terms for Product Management communication are maintained in req42 Chapter 8 (Domain Terminology).

.Further Information

See https://docs.arc42.org/section-12/[Glossary] in the arc42 documentation.

****
endif::tpo42help[]

include::../req42-chapters/08_domain-terminology.adoc[tag=domain_terms]

=== Technical Terms

ifdef::tpo42help[]
[role="tpo42help"]
****
.Content
Technical implementation terms, protocols, algorithms, and architectural concepts that developers need to understand but are not relevant for business stakeholders.

.Examples
* Protocol specifications (VISCA commands, ModBus registers)
* Technical acronyms (UART, I2C, REST, gRPC)
* Architecture patterns (CQRS, Event Sourcing, Microservices)
* Implementation details (thread pools, connection pooling, caching strategies)
****
endif::tpo42help[]

[cols="e,2e" options="header"]
|===
|Technical Term |Definition

|_<Technical-Term-1>_
|_<Technical definition for developers>_

|_<Technical-Term-2>_
|_<Technical definition for developers>_

|===
