[[section-business-goals]]
== Business Goals

//tag::vision[]
=== Vision

[role="req42help"]
****

.Content
Statement what's a mission statement for the project. It should be short. It should be actionable and everybody in the project team needs to know it.

.Motivation
That's the entire point. Remember Kennedy, this was a great one beginning on 1960s he said by the end of the decade we're going to go to the Moon.

.Notations/Tools
https://de.slideshare.net/slideshow/a-14058644/14058644[Agile Companies Go P.O.P.]
https://youtu.be/kKOqOMqp7wQ?t=383[Agile Companies Go P.O.P.]

// .More Information
//
// https://docs.req42.de/category_a/#1 in the online documentation

.tpo42 Integration
This vision will be included in arc42 Chapter 1 (Introduction and Goals) to provide business context for architectural decisions.

****

Condensed goal summary in one or two (ideally) motivating sentences.
//end::vision[]

//tag::business_goals[]
=== Goals

[role="req42help"]
****

.Content
The business objectives of your product development or project. Short and concise, understandable and transparent for your stakeholders.

.Motivation
Goals must be specified and agreed upon to the point where everyone involved has a clear idea of what is to be accomplished and in what time frames. Establishing vision and goals guides the team in developing detailed requirements and avoids fragmentation.

Perhaps your clients gave you rough goals or a vision when they entrusted you with the role of product owner. Often, however, the precision of these specifications is not enough to lead a team systematically to success.

.Notations/Tools
A wide variety of means of expression are available for defining goals, which you can choose according to your mood.

Our recommendation:

* Notation in the form of PAM (Purpose, Advantage, Metric).

Alternative forms of notation:

* Product case
* News from the Future
* Product Canvas
* Value Proposition

There is only one thing you should never do: Work without explicit goals or visions.

// .More Information
//
// https://docs.req42.de/category_a/#1 in the online documentation

.tpo42 Integration
Business goals directly influence:

* arc42 Chapter 1: Requirements overview and quality goals derivation
* arc42 Chapter 2: Business constraints that become technical constraints
* arc42 Chapter 10: Quality requirements derived from business measures
* arc42 Chapter 11: Technical risks related to business goal achievement

****

.Goal definitions according to PAM
[options="header",cols="1,2,12",stripes=even]
|===
|No
2+|Goal

.4+| 1
2+| _<Goal Name 1>_

| Purpose
| _<What do you want to achieve and why?>_

| Advantage
a|
* _<Benefit 1>_
* _<Benefit 2>_
* _<Benefit 3>_

| Measure
a|
* _<Measurable criterion 1>_
* _<Measurable criterion 2>_
* _<Measurable criterion 3>_

.4+| 2
2+| _<Goal Name 2>_

| Purpose
| _<What do you want to achieve and why?>_

| Advantage
a|
* _<Benefit 1>_
* _<Benefit 2>_
* _<Benefit 3>_

| Measure
a|
* _<Measurable criterion 1>_
* _<Measurable criterion 2>_
* _<Measurable criterion 3>_

.4+| 3
2+| _<Goal Name 3>_

| Purpose
| _<What do you want to achieve and why?>_

| Advantage
a|
* _<Benefit 1>_
* _<Benefit 2>_
* _<Benefit 3>_

| Measure
a|
* _<Measurable criterion 1>_
* _<Measurable criterion 2>_
* _<Measurable criterion 3>_

|===
//end::business_goals[]
