[[section-business-goals]]
==	Business Goals

//tag::vision[]
=== Vision
//end::vision[]

[role="req42help"]
****

.Content
Statement what's a mission statement for the project. It should be short. It should be actionable and everybody in the project team needs to know it.

.Motivation
That's the entire point. Remember Kennedy, this was a great one beginning on 1960s he said by the end of the decade we're going to go to the Moon.

.Notations/Tools
https://de.slideshare.net/slideshow/a-14058644/14058644[Agile Companies Go P.O.P.]
https://youtu.be/kKOqOMqp7wQ?t=383[Agile Companies Go P.O.P.]

// .More Information
//
//

****
//tag::vision[]
Condensed goal summary in one or two (ideally) motivating sentences.
//end::vision[]

=== Goals

[role="req42help"]
****

.Content
The business objectives of your product development or project. Short and concise, understandable and transparent for your stakeholders.

.Motivation
Goals must be specified and agreed upon to the point where everyone involved has a clear idea of what is to be accomplished and in what time frames. Establishing vision and goals guides the team in developing detailed requirements and avoids fragmentation.

Perhaps your clients gave you rough goals or a vision when they entrusted you with the role of product owner. Often, however, the precision of these specifications is not enough to lead a team systematically to success.


.Notations/Tools
A wide variety of means of expression are available for defining goals, which you can choose according to your mood.

Our recommendation:

* Notation in the form of PAM (Purpose, Advantage, Metric).

Alternative forms of notation:

* Product case
* News from the Future
* Product Canvas
* Value Proposition

There is only one thing you should never do: Work without explicit goals or visions.

// .More Information
//
// https://docs.req42.de/section-xxx in the online documentation

****

Goal definitions according to PAM:

Goal 1:

Advantage 1:

Metric 1:


Goal 2:

Advantage 2:

Metric 2:

Goal 3:

Advantage 3:

Metric 3:
