[[section-stakeholder]]
== Stakeholder

[role="req42help"]
****
.Content
A (prioritized) list of your stakeholders, along with indications of where these stakeholders can help (or hinder) the analysis work.

.Motivation
Stakeholders are the most important sources for requirements. Therefore, you should know and document them. You need to know who can help you with what or hinder you in what way.
You need to know who has what influence - and if opinions differ, you need to mediate or decide.
Without explicitly identified stakeholders, all this is difficult.

.Notations/Tools

* Tables or lists (simple form)
* Possibly stakeholder map (more complex form)

Below we have included a simple stakeholder list as an example.

The order "role before person" has been chosen deliberately. This order has proven itself since requirements normally always represent needs from the perspective of a role, but the person taking on the role can change during the project.

If required, you can also add further columns (contact data, ...) - but consider the effort for their maintenance.

// .More Information
//
// https://docs.req42.de/category_a/#2 in the online documentation

.tpo42 Integration
Stakeholder information will be included in arc42 Chapter 1 (Introduction and Goals) to provide context for architectural stakeholders and their concerns.

****

//tag::stakeholder_table[]
[cols="1,1,2,2" options="header",stripes=even]
|===
|Role        |Person       |Topic        |Influence
| _<Role-1>_ |_<Person-1>_ | _<Topic-1>_ | _<Influence-1>_
| _<Role-2>_ |_<Person-2>_ | _<Topic-2>_ | _<Influence-2>_
| _<Role-3>_ |_<Person-3>_ | _<Topic-3>_ | _<Influence-3>_
| _<Role-4>_ |_<Person-4>_ | _<Topic-4>_ | _<Influence-4>_
|===
//end::stakeholder_table[]

//tag::stakeholder_diagram[]
=== Stakeholder Relationships

[role="req42help"]
****
.Content
Optional visual representation of stakeholder relationships and communication flows.

.Motivation
Understanding stakeholder relationships can help identify communication paths and potential conflicts.

.Notations/Tools
* Simple organizational diagrams
* Stakeholder maps
* Network diagrams

****

.Stakeholder Organization
[plantuml,{plantUMLDir}/stakeholder-organization,png]
----
@startuml
skinparam defaultTextAlignment center
skinparam shadowing false
!include <tupadr3/common>
!include <office/Users/user>
!include <office/Users/users>

OFF_USER(SPONSOR, "Sponsor\n<Person>")
OFF_USER(PM, "Product Manager\n<Person>")
OFF_USER(TECH_LEAD, "Technical Lead\n<Person>")
OFF_USERS(TEAM, "Development Team")

SPONSOR -down- PM
PM -down- TECH_LEAD
TECH_LEAD -down- TEAM

@enduml
----
//end::stakeholder_diagram[]
